; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "MazliBoost"
#define MyAppVersion "0.1.1"
#define MyAppPublisher "Előd Schäffer (Mazli Studio)"
#define MyAppExeName "MazliBoost.exe"
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AE02E4DC-6D8E-411B-9533-5DBC184C0F30}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=C:\Users\Acer\Downloads\LICENSE
InfoBeforeFile=C:\Users\Acer\Downloads\info_b.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\Acer\Downloads\MazliBoost
OutputBaseFilename=mazliboost_setup
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Acer\Downloads\MazliBoost\bin\Debug\net8.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Acer\Downloads\MazliBoost\bin\Debug\net8.0-windows\MazliBoost.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Acer\Downloads\MazliBoost\bin\Debug\net8.0-windows\MazliBoost.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Acer\Downloads\MazliBoost\bin\Debug\net8.0-windows\MazliBoost.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Acer\Downloads\MazliBoost\bin\Debug\net8.0-windows\MazliBoost.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Acer\Downloads\MazliBoost\bin\Debug\net8.0-windows\System.CodeDom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Acer\Downloads\MazliBoost\bin\Debug\net8.0-windows\System.Management.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Acer\Downloads\MazliBoost\bin\Debug\net8.0-windows\runtimes\win\lib\net8.0\System.Management.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

