<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Splash\engine.png" />
    <None Remove="Splash\studio.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Splash\engine.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Splash\studio.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="Langs\*.json">
      <LogicalName>MazliBoost.Langs.%(Filename).json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
